#!/bin/bash

set -e

# Unstage the last commit but keep changes
git reset HEAD~1

# Commit each file with its own message
git add flake.lock
git commit -m "Update flake.lock to refresh input dependencies and pin new revisions for upstream Nix/NixOS, hardware, and related flakes."

git add hosts/caprica/default.nix
git commit -m "Add Caprica host configuration: enable NixOS hardware imports, set up NVIDIA graphics, pipewire audio, system packages, and user environment."

git add hosts/caprica/hardware-configuration.nix
git commit -m "Add hardware configuration for Caprica host (autogenerated by nixos-generate-config)."

git add hosts/caprica/modules/default.nix
git commit -m "Add Caprica modules default.nix to aggregate networking, plasma, misc, and services modules, and enable Flatpak."

git add hosts/caprica/modules/misc.nix
git commit -m "Add miscellaneous system packages for Caprica: xcb, text-to-speech, and utilities."

git add hosts/caprica/modules/networking.nix
git commit -m "Add Caprica networking module: configure packages, services (opensnitch, avahi, samba, NFS), and firewall rules."

git add hosts/caprica/modules/plasma.nix
git commit -m "Add system-level KDE Plasma configuration for Caprica."

git add hosts/caprica/modules/services.nix
git commit -m "Add speech-dispatcher service enablement for Caprica."

git add hosts/caprica/system/default.nix
git commit -m "Add Caprica system default.nix module placeholder."

git add hosts/hosts/pikon/nvidia.nix
git commit -m "Add NVIDIA graphics configuration for Pikon host with hybrid PRIME and kernel options."

echo "All files committed individually with appropriate messages."
echo "If you previously pushed, run: git push --force"
